### ISSUE TITLE
Merge the three projects together

### ISSUE THREAD

**Issue by sonjiku** [mbrea-c/wal-colors.nvim#3]
Hey,

This is the only solution to using pywal themes in nvim that I've found, and especially with lualine, that works properly. Thanks a lot for the work you put in.

But, having 3 repositories instead of 1 doesn't make sense at all. It is UN-intuitive and a shame to have to install 3 different plugins just to have one theme. I understand why you would want to separate the "library" from the implementations, but the library can come with the implementations as well in order for it to be usable by itself. I'm not sure if this has been used by anyone other than yourself to create plugins that call on this "library", but I don't think that will ever happen, because the color-scheme and lualine theme that you've created work great and cover the use cases for this plugin. 

If someone wanted to create a theme for another plugin that would be based on your work, they could just create a fork and then do a pull request so you can merge their additions. This way, when someone wants to use pywal colors in nvim they don't have to go for a treasure hunt around github just to get their theme-able plugins to use your "library" but just "plug and play" by installing one "mbc-wal.nvim" plugin and forgetting about it.

I'd appreciate if you combined the 3 repos so I don't have a mess on my plugin configs just to get this working.

**Comment by mbrea-c** [comment]
Hey,

Thanks for taking an interest in the project and sorry for the delay in responding, I've been away on vacation. 

I initially wanted to keep the library separate to enforce some isolation between the colorscheme itself and the "utility stuff". However I do see your point and upon further thought, I cannot think of any use cases that are not already covered by the colorscheme to justify the bad UX. We can move the colorscheme and lualine theme into this repo as a sort of "default" theme. This way users that just want to get the colorscheme only need to install a single plugin, but we still support the use of the "utility stuff" as a library should anyone else (or myself) want to do that in the future.

I can merge the changes shortly.

**Comment by mbrea-c** [comment]
Resolved with 8ac256acb320cba4c51047f4b06459359e5db954

**Comment by sonjiku** [comment]
Hey,

Hope you enjoyed your vacations in that case, and I'm glad I could contribute in some way!
