### ISSUE TITLE
The hsv_to_rgb function is returning wrong values 

### ISSUE THREAD

**Issue by Gabulhas** [mbrea-c/wal-colors.nvim#5]
Here are some examples of colors going "through" the hsv_to_rgb function
Before hsv  #1D1F28  After hsv,  #1D1E28
Before hsv  #F37F97  After hsv,  #F37E97
Before hsv  #5ADECD  After hsv,  #59DECC
Before hsv  #8897F4  After hsv,  #8896F4
Before hsv  #79E6F3  After hsv,  #78E5F3
Before hsv  #18E3C8  After hsv,  #18E3C7
Before hsv  #FF8037  After hsv,  #FF8037
Before hsv  #3FDCEE  After hsv,  #3EDBEE

My theme is looking off from what I have on my terminal, and it's happening because

**Comment by mbrea-c** [comment]
Interesting, now that you mention it I have also noticed that the colors are slightly off from my terminal. 

> My theme is looking off from what I have on my terminal, and it's happening because

Did you end up finding the bug?

**Comment by Gabulhas** [comment]
Yeap
Going to make a PR with the fix.

**Comment by Gabulhas** [comment]
Done ;)

**Comment by mbrea-c** [comment]
PR merged :)
